name: Build Application

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        variants:
          - runner: ubuntu-latest
            task: linux:package
          - runner: ubuntu-24.04-arm
            task: linux:package
          - runner: macos-latest
            task: darwin:package:universal
          - runner: windows-latest
            task: windows:build:native
    runs-on: ${{ matrix.variants.runner }}
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-go@v6
        with:
          go-version: ">=1.24"
          check-latest: true
      - name: Install System Dependencies
        if: matrix.variants.runner == 'ubuntu-latest' || matrix.variants.runner == 'ubuntu-24.04-arm'
        run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.1-dev
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v3/cmd/wails3@latest
      - name: Build Application
        run: wails3 task ${{ matrix.variants.task }}
      - name: Build Application Windows ARM
        if: matrix.variants.runner == 'windows-latest'
        run: wails3 task ${{ matrix.variants.task }} GOARCH=arm64
      - uses: actions/upload-artifact@v6
        with:
          name: moonshot-${{ matrix.variants.runner }}
          path: bin
