name: Build Application

on:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        variants:
          - runner: ubuntu-latest
            platform: linux/amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
          - runner: macos-latest
            platform: darwin/universal
          - runner: windows-latest
            platform: windows/amd64,windows/arm64
    runs-on: ${{ matrix.variants.runner }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ">=1.24"
          check-latest: true
      - name: Install System Dependencies
        if: matrix.variants.runner == 'ubuntu-latest' || matrix.variants.runner == 'ubuntu-24.04-arm'
        run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.1-dev
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Build Application
        run: wails build --tags webkit2_41 --platform ${{ matrix.variants.platform }}
      - uses: actions/upload-artifact@v6
        with:
          name: moonshot-${{ matrix.variants.runner }}
          path: build/bin
